version: '3.9'
services:

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - node-network

  node:
    build: ./server
    # image: node-app
    container_name: "node-server"
    working_dir: /src
    environment:
      - MONGO_URI=mongodb://mongo:27017
    ports:
      - 5050:5050
    depends_on:
      - mongo
    volumes:
      - ./server/:/src
    networks:
      - node-network

  react:
    build: ./client
    # image: node:alpine
    container_name: react-client
    ports:
      - 3000:3000
    working_dir: /app
    depends_on:
      - node
      - mongo
    networks:
      - node-network
    volumes:
      - type: bind
        source: ./client
        target: /app
    tty: true

volumes:
  mongodb:


networks:
  node-network:
    driver: bridge
